### ISSUE TITLE
request to NOT do a planned feature

### ISSUE THREAD

**Issue by wackoamd1** [astronotter/ottercraft#1]
"Giant otters which will be rideable on both land and water".
please drop that planned feature . 
it would shatter the cuteness level of these guys
 
the idea and direction of the mod is awesome as it is ,
 i would love to see them slide down and play around more and whatever u can think off.
 
and since im here anyway , when u breed otters they come out the same size as the parents could u make them smaller and let them "grow up"

**Comment by astronotter** [comment]
Hi, glad you like it!

The giant otters will be a separate entity type, so they shouldn't detract from the current otters' cuteness in any way (though that may be unfair to the giant otters, which can be cute in their own right! :) Regardless, I will make sure they are configurable so you can set them to not spawn if you so choose.

Thanks for bringing the child size issue to my attention, a fix has been pushed and will be in the next version we release.
