### ISSUE TITLE
[SUGGESTION] Add a config

### ISSUE THREAD

**Issue by Sunconure11** [astronotter/ottercraft#2]
The mod could seriously benefit from this, so we can turn up or down the rate at which otters spawn

**Comment by astronotter** [comment]
Hi thanks for the feedback! I've actually had this planned for a while but I've been busy with school. I'll keep this issue open until I do so but I just wanted to say I definitely agree and will be adding it!

**Comment by Sunconure11** [comment]
Another note, 1.18.2 is out. Might want to see how that affects things

**Comment by astronotter** [comment]
The latest release on Curseforge now uses a configuration file.
